Controllers/CustomersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication13.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Xml.Linq;
using static MessagePack.MessagePackSerializer;

namespace WebApplication13.Controllers
{


    public class CustomersController : Controller
    {
            private readonly BLM19417EContext _context;
            public CustomersController(BLM19417EContext context)
            {
                _context = context;
            }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
     




            return View(await _context.Customers.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> searchB(string search)
        {
            var searching = _context.Customers.Where(t => t.FirstName.ToLower().Contains(search.ToLower()));
            return View(nameof(Index), await searching.ToListAsync());
        }


        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
            {
                if (id == null || _context.Customers == null)
                {
                    return NotFound();
                }

                var customer = await _context.Customers
                    .FirstOrDefaultAsync(m => m.CustomerId == id);
                if (customer == null)
                {
                    return NotFound();
                }

                return View(customer);
            }



        // GET: Customers/Create
        public IActionResult Create()
        {
            var listele = (from type in _context.CosRepresantatives
                           select
                           new SelectListItem()
                           {
                               Text = type.FirstName,
                               Value = type.CosRepresantativeId.ToString()
                           }

                  ).ToList();

            listele.Insert(0, new SelectListItem()
            {

                Text = "      ",
                Value = String.Empty
            });


            ViewBag.ListofCust = listele;



            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind("CustomerId,FirstName,LastName,country,phone,age,point,CosRepresantativeId")] Customer customer)
        {
            var listele = (from type in _context.CosRepresantatives
                           select
                           new SelectListItem()
                           {
                               Text = type.FirstName,
                               Value = type.CosRepresantativeId.ToString()
                           }

           ).ToList();

            listele.Insert(0, new SelectListItem()
            {

                Text = "      ",
                Value = String.Empty
            });


            ViewBag.ListofCust = listele;


            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Customer Created Successfully!";
                return RedirectToAction(nameof(Index));
            }
          
            return View(customer);
        }


        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
            {
                if (id == null || _context.Customers == null)
                {
                    return NotFound();
                }

                var customer = await _context.Customers.FindAsync(id);
                if (customer == null)
                {
                    return NotFound();
                }
                return View(customer);
            }



        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, [Bind("CustomerId,FirstName,LastName,country,phone,age,point,CusRepresantativeId")] Customer customer)
            {
                var cus = await _context.Customers.FindAsync(id);
                _context.Entry(cus).State = EntityState.Detached;
                if (id != customer.CustomerId)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(customer);
                        await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Customer Updated Successfully!";
                }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!CustomerExists(customer.CustomerId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(customer);
            }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
            {
                if (id == null || _context.Customers == null)
                {
                    return NotFound();
                }

                var customer = await _context.Customers
                    .FirstOrDefaultAsync(m => m.CustomerId == id);
                if (customer == null)
                {
                    return NotFound();
                }

                return View(customer);
            }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                if (_context.Customers == null)
                {
                    return Problem("Entity set 'BLM19417EContext.Customers'  is null.");
         
            }
                var customer = await _context.Customers.FindAsync(id);
                if (customer != null)
                {
                    _context.Customers.Remove(customer);
                }

                await _context.SaveChangesAsync();
            TempData["AlertMessage"] = "Customer Deleted Successfully!";
            return RedirectToAction(nameof(Index));
            }

            private bool CustomerExists(int id)
            {
                return _context.Customers.Any(e => e.CustomerId == id);
            }
        }
    }


Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using WebApplication13.Models;

namespace WebApplication13.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly BLM19417EContext _context;

        public DepartmentsController(BLM19417EContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Departments.ToListAsync());
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.Include(d => d.CosRepresantatives)
                .FirstOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> searchC(string search)
        {
            var searching = _context.Departments.Where(t => t.DepartmentName.ToLower().Contains(search.ToLower()));
            return View(nameof(Index), await searching.ToListAsync());
        }


        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DepartmentId,DepartmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Department Created Successfully!";
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DepartmentId,DepartmentName")] Department department)
        {
            if (id != department.DepartmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Department Updated Successfully!";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.DepartmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Departments == null)
            {

                return NotFound();
            }

            var department = await _context.Departments
                .FirstOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
         
                return NotFound();
            }
         
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Departments == null)
            {

                return Problem("Entity set 'BLM19417EContext.Departments'  is null.");
            }
            var department = await _context.Departments.FindAsync(id);
     
            if (department != null)
            {
                _context.Departments.Remove(department);
                TempData["AlertMessage"] = "Department Deleted Successfully!";
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
            return _context.Departments.Any(e => e.DepartmentId == id);
        }
    }
}


Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication13.Models;

namespace WebApplication13.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ScoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using WebApplication13.Models;
using System.Runtime.Intrinsics.Arm;
using static System.Formats.Asn1.AsnWriter;
using System.Xml.Linq;

namespace WebApplication13.Controllers
{
    public class ScoreController : Controller
    {
        private readonly BLM19417EContext _context;

        public ScoreController(BLM19417EContext context)
        {
            _context = context;
        }

        // GET: Score
        public async Task<IActionResult> Index()
        {
            var score =_context.Customers 
            .Where(x => x.CosRepresantativeId == x.CosRepresantative.CosRepresantativeId )
            .GroupBy(x => new { x.CosRepresantative.CosRepresantativeId, x.CosRepresantative.FirstName })
            .Select(g => new Score
            
            {
                CosRepresantativeId = g.Key.CosRepresantativeId,
        Name = g.Key.FirstName,
        totalScore = g.Sum(x => x.point)        
    }).ToList(); 
            //.OrderBy(x => x.g.totalScore)
            return View(score);
        }



  
    }



}


Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

   

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/carousel/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>
  <body data-new-gr-c-s-check-loaded="14.1088.0" data-gr-ext-installed="">


    <main role="main">
       

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class=""></li>
          <li data-target="#myCarousel" data-slide-to="1" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item">
            <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item active">
            <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>One more for good measure.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
          <div class="col-lg-4">
                    <img class="rounded-circle" src="https://img.freepik.com/free-photo/successful-happy-business-team_53876-74892.jpg?w=2000" alt="Generic placeholder image" width="140" height="140">
            <h2>Departments</h2>
            <p> Here you can access the department table so you can create, delete and update new departments in the database.</p>
                    <p> <a class="btn btn-secondary" asp-area="" asp-controller="Departments" asp-action="Index">>>View<<</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
                    <img class="rounded-circle" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXWJSWHa75UT4ex4f6wkGP8gT-sbA7H6TGsw&usqp=CAU" alt="Generic placeholder image" width="140" height="140">
            <h2>Represantatives</h2>
                    <p>You can reach the customer representatives from here, so you can see the customer representatives in the database, add, delete or update new customer representatives.</p>
                    <p> <a class="btn btn-secondary" asp-area="" asp-controller="CosRepresantatives" asp-action="Index">>>View<<</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
                    <img class="rounded-circle" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8TcP68wLsXFMGOVgZJGjbZolv-5XwIDN1mg&usqp=CAU" alt="Generic placeholder image" width="140" height="140">
            <h2>Customers</h2>
                    <p>  Here you can access the Customer table. So it can view the customers in the database. You can add new customers, delete or update them.</p>
                    <p> <a class="btn btn-secondary" asp-area="" asp-controller="Customers" asp-action="Index">>>View<<</a></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">Customer Represantative of the month <span class="text-muted">is selected based on customer point.</span></h2>
                    <p class="lead">Our company works with high quality. The opinion of our customers is very important to us. For this reason, we ask all our  customers to choose their own customer representatives and also to give a point to the customer representative after the service they receive. These points are summed up and the points of our customer representatives are calculated. In this way, we see which of our employees are satisfied or dissatisfied, and necessary warnings and rewards are made.</p> 
                    <a class="btn btn-secondary" asp-area="" asp-controller="Score" asp-action="Index">Look at Table</a>
                    </div>
          <div class="col-md-5">
                    <img class="featurette-image img-fluid mx-auto" data-src="holder.js/300x300/auto" alt="300x300" style="width: 300px; height: 300px;" src="https://media.istockphoto.com/id/583848942/tr/vekt%C3%B6r/employee-of-the-month-award.jpg?s=612x612&w=is&k=20&c=nIAOlr7W15Wss7kVI1IMTVNg0qjj2eehJlF6gAjN2cA="
        </div>
            </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Customers can add <span class="text-muted">Requests or Complaints.</span></h2>
             <p class="lead">Our customers' problems are always our problems. That's why we have an indicator so that we can access our customers' requests and complaints more easily, it's just that we can observe the problems or requests more easily.</p>
                        <a class="btn btn-secondary" asp-area="" asp-controller="RequestComplaints" asp-action="Index">Look at Request or Complaint Box</a></p>
         </div>
          <div class="col-md-5 order-md-1">
                        <img class="featurette-image img-fluid mx-auto" data-src="holder.js/300x300/auto" alt="300x300" src="https://p.calameoassets.com/191123010416-2b6a95feaa46bc3523e188fc63104432/p1.jpg" data-holder-rendered="true" style="width: 300px; height: 300px;">
          </div>
        </div>

        <hr class="featurette-divider"
        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">And lastly, <span class="text-muted">thank you to chosing to us.</span></h2>
                    <p class="lead">As you can see, you can add a customer representative, customer, department, or request complaint from this web page, and you can perform various operations simultaneously with the database.</p>
          </div>
          <div class="col-md-5">
                    <img class="featurette-image img-fluid mx-auto" data-src="holder.js/300x200/auto" alt="300x200" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1M72ufNdXaQd7PmrrSpg0tpaqT7apQhM2gA&usqp=CAU" data-holder-rendered="true" style="width: 300px; height: 200px;">
          </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div><!-- /.container -->

      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
     
     
      </footer>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
  

<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500" viewBox="0 0 500 500" preserveAspectRatio="none" style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs><style type="text/css"></style></defs><text x="0" y="25" style="font-weight:bold;font-size:25pt;font-family:Arial, Helvetica, Open Sans, sans-serif">500x500</text></svg></body><grammarly-desktop-integration data-grammarly-shadow-root="true"></grammarly-desktop-integration></html>