Models/Score.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace WebApplication13.Models
{
    public partial class Score
    {

        [Key]
        public int CosRepresantativeId { get; set; }
        public String? Name { get; set; }
        public int? totalScore { get; set;}

        public virtual Customer? Customer { get; set; }
        public virtual CosRepresantative? CosRepresantative { get; set; }


    }
}

Controllers/CosRepresantativesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication13.Models;
using Microsoft.AspNetCore.Mvc;
using System.Xml.Linq;
using static MessagePack.MessagePackSerializer;

namespace WebApplication13.Controllers
{
    public class CosRepresantativesController : Controller
    {

        private readonly BLM19417EContext _context;
        public CosRepresantativesController(BLM19417EContext context)
        {
            _context = context;
        }

        // GET: CosRepresantatives
        public async Task<IActionResult> Index()
        {

            return View(await _context.CosRepresantatives.ToListAsync());
        }

        // GET: CosRepresantatives/Details/5
        public async Task<IActionResult> Details(int? id)
        {

 


            if (id == null || _context.CosRepresantatives == null)
            {
                return NotFound();
            }
     
            var cosrepresantative = await _context.CosRepresantatives.Include(d => d.Customers)
                .FirstOrDefaultAsync(m => m.CosRepresantativeId == id);
            if (cosrepresantative == null)
            {
                return NotFound();
            }

            return View(cosrepresantative);
        }
        [HttpPost]
        public async Task<IActionResult> searchA(string search)
        {
            var searching = _context.CosRepresantatives.Where(t => t.FirstName.ToLower().Contains(search.ToLower()));
            return View(nameof(Index), await searching.ToListAsync());
        }



        // GET: CosRepresantatives/Create
        public IActionResult Create()
        {
            var list = (from type in _context.Departments
                           select
                           new SelectListItem()
                           {
                               Text = type.DepartmentName,
                               Value = type.DepartmentId.ToString()
                           }

                  ).ToList();

            list.Insert(0, new SelectListItem()
            {

                Text = "      ",
                Value = String.Empty
            });


            ViewBag.ListofCust = list;



            return View();
        }

        // POST: CosRepresantatives/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind("CosRepresantativeId,FirstName,LastName,Country,DepartmentId")] CosRepresantative cosrepresantative)
        {
            var list = (from type in _context.Departments
                           select
                           new SelectListItem()
                           {
                               Text = type.DepartmentName,
                               Value = type.DepartmentId.ToString()
                           }

           ).ToList();

            list.Insert(0, new SelectListItem()
            {

                Text = "      ",
                Value = String.Empty
            });


            ViewBag.ListofCust = list;


            if (ModelState.IsValid)
            {
                _context.Add(cosrepresantative);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Cosrepresantative Created Successfully!";
                return RedirectToAction(nameof(Index));
            }
            return View(cosrepresantative);
        }

        // GET: CosRepresantatives/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CosRepresantatives == null)
            {
                return NotFound();
            }

            var cosrepresantative = await _context.CosRepresantatives.FindAsync(id);
            if (cosrepresantative == null)
            {
                return NotFound();
            }
            return View(cosrepresantative);
        }


        // POST: CosRepresantatives/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CosRepresantativeId,FirstName,LastName,Country,DepartmentId")] CosRepresantative cosrepresantative)
        {
            var cosrep = await _context.CosRepresantatives.FindAsync(id);
            _context.Entry(cosrep).State = EntityState.Detached;
            if (id != cosrepresantative.CosRepresantativeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cosrepresantative);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Cosrepresantative Updated Successfully!";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CosRepresantativeExists(cosrepresantative.CosRepresantativeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cosrepresantative);
        }

        // GET: CosRepresantatives/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CosRepresantatives == null)
            {
                return NotFound();
            }

            var cosrepresantative = await _context.CosRepresantatives
                .FirstOrDefaultAsync(m => m.CosRepresantativeId == id);
            if (cosrepresantative == null)
            {
                return NotFound();
            }

            return View(cosrepresantative);
        }


        // POST: CosRepresantatives/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CosRepresantatives == null)
            {
                return Problem("Entity set 'BLM19417EContext.CosRepresantatives'  is null.");
            }
            var cosrepresantative = await _context.CosRepresantatives.FindAsync(id);
            if (cosrepresantative != null)
            {
                _context.CosRepresantatives.Remove(cosrepresantative);
            }

            await _context.SaveChangesAsync();
            TempData["AlertMessage"] = "Cosrepresantative Deleted Successfully!";
            return RedirectToAction(nameof(Index));
        }

        private bool CosRepresantativeExists(int id)
        {
            return _context.CosRepresantatives.Any(e => e.CosRepresantativeId == id);
        }
    }



}


Controllers/ScoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using WebApplication13.Models;
using System.Runtime.Intrinsics.Arm;
using static System.Formats.Asn1.AsnWriter;
using System.Xml.Linq;

namespace WebApplication13.Controllers
{
    public class ScoreController : Controller
    {
        private readonly BLM19417EContext _context;

        public ScoreController(BLM19417EContext context)
        {
            _context = context;
        }

        // GET: Score
        public async Task<IActionResult> Index()
        {
            var score =_context.Customers 
            .Where(x => x.CosRepresantativeId == x.CosRepresantative.CosRepresantativeId )
            .GroupBy(x => new { x.CosRepresantative.CosRepresantativeId, x.CosRepresantative.FirstName })
            .Select(g => new Score
            
            {
                CosRepresantativeId = g.Key.CosRepresantativeId,
        Name = g.Key.FirstName,
        totalScore = g.Sum(x => x.point)        
    }).ToList(); 
            //.OrderBy(x => x.g.totalScore)
            return View(score);
        }



  
    }



}


Views/Score/Index.cshtml


@model IEnumerable<WebApplication13.Models.Score>

@{
    ViewData["Title"] = "Index";
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/bootstrap.min.css" rel=stylesheet/>
    <script src="https://kit.fontawesome.com/add66288fd.js" crossorigin="anonymous"></script>
    <title>       </title>
     
</head>

    <style>
        body {
            background-color: white;
        }
        h1 {
    z-index: 99999;
    overflow: hidden;
    margin-left:auto;
    margin-right:auto;
}

        table {
   
            border-collapse: collapse;
            width: 375px;
            margin: auto;
        }

        td, th {
            border: 1px solid black;
            text-align: left;
            vertical-align: middle;
            padding: 3px;
        }

        tr:nth-child(even) {
            background-color: lightgreen;
        }

        tr:nth-child(odd) {
            background-color:orange;
        }

      tr:first-child {
        background-color: white;
    }


        ul {
            text-align: center;
            list-style-position: inside;
        }
        h1{
            color:darkslategrey;
            text-align: center;
    }
    </style>
<body>
    <h1><i class="fa-solid fa-award"></i> &nbsp;&nbsp;Scores Table Of Represantatives</h1>
   
    <table class="table">
        <thead>
            <tr>
              
                <th>
                    @Html.DisplayNameFor(model => model.CosRepresantativeId)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.totalScore)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CosRepresantativeId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.totalScore)
                    </td>
                  
                    <td>

                        <a asp-area="" asp-controller="CosRepresantatives" asp-action="Details" asp-route-id="@item.CosRepresantativeId">Detail of Represantative</a>
                   
                    </td>
                </tr>
            }
        </tbody>
    </table>

</body>
</html>
