Models/Customer.cs
using System.Xml.Schema;

namespace WebApplication13.Models
{
    public partial class Customer
    {
        public Customer ()
        {
            RequestComplaints = new HashSet<RequestComplaint>();
            Score = new HashSet<Score>();

        }
        public int CustomerId { get; set; }
        public string?FirstName { get; set; }
        public string? LastName { get; set; }
        public string? country { get; set; }
        public string? phone { get; set; }
        public string? age { get; set; }
        public int? point { get; set; }
        public int? CosRepresantativeId { get; set; }
     
        public virtual CosRepresantative? CosRepresantative { get; set; }
        public virtual ICollection<RequestComplaint>? RequestComplaints { get; set; }
        public virtual ICollection<Score>? Score { get; set; }


    }
}

Controllers/CustomersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication13.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Xml.Linq;
using static MessagePack.MessagePackSerializer;

namespace WebApplication13.Controllers
{


    public class CustomersController : Controller
    {
            private readonly BLM19417EContext _context;
            public CustomersController(BLM19417EContext context)
            {
                _context = context;
            }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
     




            return View(await _context.Customers.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> searchB(string search)
        {
            var searching = _context.Customers.Where(t => t.FirstName.ToLower().Contains(search.ToLower()));
            return View(nameof(Index), await searching.ToListAsync());
        }


        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
            {
                if (id == null || _context.Customers == null)
                {
                    return NotFound();
                }

                var customer = await _context.Customers
                    .FirstOrDefaultAsync(m => m.CustomerId == id);
                if (customer == null)
                {
                    return NotFound();
                }

                return View(customer);
            }



        // GET: Customers/Create
        public IActionResult Create()
        {
            var listele = (from type in _context.CosRepresantatives
                           select
                           new SelectListItem()
                           {
                               Text = type.FirstName,
                               Value = type.CosRepresantativeId.ToString()
                           }

                  ).ToList();

            listele.Insert(0, new SelectListItem()
            {

                Text = "      ",
                Value = String.Empty
            });


            ViewBag.ListofCust = listele;



            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind("CustomerId,FirstName,LastName,country,phone,age,point,CosRepresantativeId")] Customer customer)
        {
            var listele = (from type in _context.CosRepresantatives
                           select
                           new SelectListItem()
                           {
                               Text = type.FirstName,
                               Value = type.CosRepresantativeId.ToString()
                           }

           ).ToList();

            listele.Insert(0, new SelectListItem()
            {

                Text = "      ",
                Value = String.Empty
            });


            ViewBag.ListofCust = listele;


            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Customer Created Successfully!";
                return RedirectToAction(nameof(Index));
            }
          
            return View(customer);
        }


        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
            {
                if (id == null || _context.Customers == null)
                {
                    return NotFound();
                }

                var customer = await _context.Customers.FindAsync(id);
                if (customer == null)
                {
                    return NotFound();
                }
                return View(customer);
            }



        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, [Bind("CustomerId,FirstName,LastName,country,phone,age,point,CusRepresantativeId")] Customer customer)
            {
                var cus = await _context.Customers.FindAsync(id);
                _context.Entry(cus).State = EntityState.Detached;
                if (id != customer.CustomerId)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(customer);
                        await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Customer Updated Successfully!";
                }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!CustomerExists(customer.CustomerId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(customer);
            }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
            {
                if (id == null || _context.Customers == null)
                {
                    return NotFound();
                }

                var customer = await _context.Customers
                    .FirstOrDefaultAsync(m => m.CustomerId == id);
                if (customer == null)
                {
                    return NotFound();
                }

                return View(customer);
            }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                if (_context.Customers == null)
                {
                    return Problem("Entity set 'BLM19417EContext.Customers'  is null.");
         
            }
                var customer = await _context.Customers.FindAsync(id);
                if (customer != null)
                {
                    _context.Customers.Remove(customer);
                }

                await _context.SaveChangesAsync();
            TempData["AlertMessage"] = "Customer Deleted Successfully!";
            return RedirectToAction(nameof(Index));
            }

            private bool CustomerExists(int id)
            {
                return _context.Customers.Any(e => e.CustomerId == id);
            }
        }
    }


Controllers/RequestComplaintsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication13.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using WebApplication13.Models;

namespace WebApplication13.Controllers
{
    public class RequestComplaintsController : Controller
    {

            private readonly BLM19417EContext _context;

            public RequestComplaintsController(BLM19417EContext context)
            {
                _context = context;
            }

        // GET: RequestComplaints
           public async Task<IActionResult> Index()
            {
                return View(await _context.RequestComplaints.ToListAsync());
            }

        // GET: RequestComplaints/Details/5
        public async Task<IActionResult> Details(int? id)
            {
                if (id == null || _context.RequestComplaints == null)
                {
                    return NotFound();
                }

                var request = await _context.RequestComplaints.Include(d => d.Customer)
                    .FirstOrDefaultAsync(m => m.CustomerId == id);
                if (request == null)
                {
                    return NotFound();
                }

                return View(request);
            }

        // GET: RequestComplaints/Create
        public IActionResult Create()
            {
            ViewBag.Type = _context.RequestComplaints.ToString();
            return View();
            }

        // POST: RequestComplaints/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create([Bind("RequestComplaintId,Type,Text,CustomerId")] RequestComplaint request)
            {
            ViewBag.Type = request.Type;
            if (ModelState.IsValid)
                {
                    _context.Add(request);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(request);
            }

        // GET: RequestComplaints/Edit/5
        public async Task<IActionResult> Edit(int? id)
            {
                if (id == null || _context.RequestComplaints == null)
                {
                    return NotFound();
                }

                var request = await _context.RequestComplaints.FindAsync(id);
                if (request == null)
                {
                    return NotFound();
                }
                return View(request);
            }

        // POST: RequestComplaints/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, [Bind("RequestComplaintId,Type,Text,CustomerId")] RequestComplaint request)
            {
                if (id != request.RequestComplaintId)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(request);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!RequestComplaintExists(request.RequestComplaintId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(request);
            }

        // GET: RequestComplaints/Delete/5
        public async Task<IActionResult> Delete(int? id)
            {
                if (id == null || _context.RequestComplaints == null)
                {
                    return NotFound();
                }

                var request = await _context.RequestComplaints
                    .FirstOrDefaultAsync(m => m.RequestComplaintId == id);
                if (request == null)
                {
                    return NotFound();
                }

                return View(request);
            }

        // POST: RequestComplaints/Delete/5
        [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                if (_context.RequestComplaints == null)
                {
                    return Problem("Entity set 'BLM19417EContext.RequestComplaints'  is null.");
                }
                var request = await _context.RequestComplaints.FindAsync(id);
                if (request != null)
                {
                    _context.RequestComplaints.Remove(request);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            private bool RequestComplaintExists(int id)
            {
                return _context.RequestComplaints.Any(e => e.RequestComplaintId == id);
            }
        }
    }


Views/Customers/Create.cshtml
@model WebApplication13.Models.Customer

@{
    ViewData["Title"] = "Create";
}
<!doctype html>
<html lang="en">
<head ruanat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/add66288fd.js" crossorigin="anonymous"></script>
</head>

<h1>Create</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @using (Html.BeginForm())
            {
                <div class="form-group">
                    <label asp-for="CustomerId" class="control-label"></label>
                    <input asp-for="CustomerId" class="form-control" />
                    <span asp-validation-for="CustomerId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
        <div class="form-group">
                    <label asp-for="country" class="control-label"></label>
                    <input asp-for="country" class="form-control" />
                    <span asp-validation-for="country" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="phone" class="control-label"></label>
                    <input asp-for="phone" class="form-control" />
                    <span asp-validation-for="phone" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="age" class="control-label"></label>
                    <input asp-for="age" class="form-control" />
                    <span asp-validation-for="age" class="text-danger"></span>
                </div>
       
  
                   <br />
                 <p> Select Your Represantative</p>
                
                <div class="form-group">

                    @Html.DropDownListFor(m=>m.CosRepresantativeId, new SelectList(ViewBag.ListofCust, "Value", "Text"), "No choosen yet", new {@onChange="selectedText(this)"})

                    @* <input type="text" id="txt" readonly="readonly" name="typeSelected"></input>*@

                </div>
                <br />
                <div class="form-group">
                    <fieldset>
                        Point for your Represantative;
                        <select id="point" name="point">

                            <option value=""></option>

                            <option selected="selected" value="1">1</option>

                            <option value="2">2</option>

                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>

                        </select>
                </div>
             
                <br />
            <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" style="background-color: green" />
                </div>

            }



        </form>
    </div>
</div>

<div>
    <a asp-action="Index"> <i class="fa-solid fa-backward"></i>&nbsp;Back to the Table </a> &nbsp;&nbsp;
   
</div>
</html>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script>
    function selectedText(ddlitem) {
        var setvalue = ddlitem.value;
        var seltext = ddlitem.options[ddlitem.selectedIndex].innerHTML;
        $('#txt').val(seltext);

    }
</script>

Views/Customers/Delete.cshtml
@model WebApplication13.Models.Customer

@{
    ViewData["Title"] = "Delete";
}
<!doctype html>
<html lang="en">
<head ruanat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/add66288fd.js" crossorigin="anonymous"></script>
</head>

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CosRepresantativeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CosRepresantativeId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CustomerId" />
        <input type="submit" value="Delete" class="btn btn-danger" style=" background-color: #f44336;" /> |
        <a asp-action="Index"> <i class="fa-solid fa-backward"></i>&nbsp;Back to the Table </a> &nbsp;&nbsp;|&nbsp;&nbsp;
    </form>
</div>
</html>

Views/Customers/Details.cshtml
@model WebApplication13.Models.Customer
@{
    ViewData["Title"] = "Details";
}
<!doctype html>
<html lang="en">
<head ruanat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/add66288fd.js" crossorigin="anonymous"></script>
</head>
<h1>Details</h1>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.age)
        </dt>
        <dd class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CosRepresantativeId)
        </dd>
        <dt class = "col-sm-10">
            @Html.DisplayFor(model => model.CosRepresantativeId)
        </dt>
    </dl>
</div>
<div>
    <a asp-action="Index"> <i class="fa-solid fa-backward"></i>&nbsp;Back to the Table </a> &nbsp;&nbsp;|&nbsp;&nbsp;
    <a asp-action="Edit" asp-route-id="@Model?.CustomerId">  <i class="fa-regular fa-pen-to-square"></i> &nbsp;Edit</a>
    <a asp-area="" asp-controller="RequestComplaints" asp-action="Create">Add - Request or Complaint<i class="fa-solid fa-envelope"></i></a>

</div>
</html>

Views/Customers/Edit.cshtml
@model WebApplication13.Models.Customer

@{
    ViewData["Title"] = "Edit";
}
<head ruanat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/add66288fd.js" crossorigin="anonymous"></script>
</head>

<h1>Edit</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CosRepresantativeId" class="control-label"></label>
                <input asp-for="CosRepresantativeId" class="form-control" />
                <span asp-validation-for="CosRepresantativeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="country" class="control-label"></label>
                <input asp-for="country" class="form-control" />
                <span asp-validation-for="country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone" class="control-label"></label>
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="age" class="control-label"></label>
                <input asp-for="age" class="form-control" />
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"> <i class="fa-solid fa-backward"></i>&nbsp;Back to the Table </a> &nbsp;&nbsp;|
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Customers/Index.cshtml
@model IEnumerable<WebApplication13.Models.Customer>

@{
    ViewData["Title"] = "Index";
}

<br />

<!doctype html>
<html lang="en">
<head ruanat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/add66288fd.js" crossorigin="anonymous"></script>
</head>
<style>
    body {
        background-color: white;
    }

    table {
        border-collapse: collapse;
        width: 375px;
        margin: auto;
    }

    td, th {
        border: 1px solid black;
        text-align: left;
        vertical-align: middle;
        padding: 3px;
    }

    tr:nth-child(even) {
        background-color: lightgrey;
    }

    tr:nth-child(even) {
        background-color:;
    }

    ul {
        text-align: center;
        list-style-position: inside;
    }

    h1 {
        color: darkslategrey;
        text-align: center;
    }
   
</style>

<body>
    <h1>CUSTOMERS &nbsp;&nbsp;<i class="fa-sharp fa-solid fa-people-group"></i> </h1>




    @if (TempData["AlertMessage"] != null)
    {
        <div class="alert alert-success">
            <strong>Success!</strong> @TempData["AlertMessage"]
        </div>
    }
    <div></div>

    <p>
        <a style="  !important;" asp-action="Create"><i class="fa-solid fa-user-plus"></i> Create New Cosrepresantative</a>
    </p>
    <form asp-action="searchB">
        <input type="text" name="search" id="search" />
        <button type="submit" style="background-color:lightgrey;!important; color:white" class="btn"><i class="fa fa-search text-white"></i>Search Customer </button>
    </form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.phone)
            </th>
                <th>
                    @Html.DisplayNameFor(model => model.country)
                </th>



            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerId)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                <td>
                    @Html.DisplayFor(modelItem => item.country)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.phone)
                </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.age)
                    </td>
              <td>
                        <a asp-action="Edit" asp-route-id="@item.CustomerId"><i class="fa-solid fa-pen-to-square"></i></a>  |
                        <a asp-action="Details" asp-route-id="@item.CustomerId"><i class="fa-solid fa-circle-info"></i></a>  |
                        <a asp-action="Delete" asp-route-id="@item.CustomerId"><i class="fa-solid fa-delete-left"></i></a> |
                      
                  
                  
            </td>
        </tr>

}
        </tbody>
    </table>
    <div>
        <a asp-area="" asp-controller="RequestComplaints" asp-action="Create">Add - Request or Complaint<i class="fa-solid fa-envelope"></i></a>
    </div>
   
</body>

</html>